# Generated by Django 5.2.6 on 2025-09-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='company', max_length=50)),
                ('vin', models.CharField(help_text='vehicle identification number', max_length=17)),
                ('model', models.CharField(help_text='car model', max_length=50)),
                ('price', models.IntegerField(help_text='price of the car', max_length=15)),
                ('year', models.IntegerField()),
                ('color', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
