# Generated by Django 5.2.6 on 2025-09-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayapp', '0002_car_delete_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(help_text='price of the car'),
        ),
    ]
