# Generated by Django 5.2.6 on 2025-09-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayapp', '0003_alter_car_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='NAME', max_length=50)),
                ('umis_id', models.CharField(help_text='UMID ID', max_length=17)),
                ('dept', models.CharField(help_text='DEPARTMENT', max_length=50)),
                ('year', models.IntegerField(help_text='YEAR')),
                ('ref_no', models.IntegerField()),
                ('dob', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
